name: Build TWRP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Free disk space
      run: |
        dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
        df -h
        sudo apt-get remove -y '^ghc-8.*'
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
        sudo apt-get autoremove -y
        sudo apt-get clean
        df -h
        rm -rf /usr/share/dotnet/
        df -h
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

    - name: Configure git and repo
      run: |
        git config --global user.name "Name"
        git config --global user.email "email@example.com"
        mkdir ~/bin
        PATH=~/bin:$PATH
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo

    - name: Initialize TWRP repository
      run: |
        mkdir twrp && cd twrp
        ~/bin/repo init https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
        ~/bin/repo sync

    - name: Prepare device tree
      run: |
        # 这里需要您提供设备的源代码树路径
        git clone https://github.com/twrpdtgen/android_device_xiaomi_opal.git

    - name: Build TWRP image
      run: |
        . build/envsetup.sh
        lunch omni_codename-eng
        mka recoveryimage

    - name: LFT
      run: ls -lhsa

    - name: Upload TWRP image
      uses: actions/upload-artifact@v2
      with:
        name: twrp-image
        path: opal/recovery.img
        
